import asyncio
from sqlalchemy import select

from app.config import get_settings
from app.database import Base, SessionLocal, engine
from app.enums import AssetType, HostStatus, HttpMethod, PortState, ProjectStatus, Protocol, Severity, VulnerabilityStatus
from app.models import Endpoint, Host, Port, Project, ProjectMember, Service, User, Vulnerability, VulnerabilityAsset
from app.services import UserService


async def reset_schema() -> None:
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.drop_all)
        await conn.run_sync(Base.metadata.create_all)


async def seed_demo_data() -> None:
    settings = get_settings()
    async with SessionLocal() as db:
        await UserService(db).bootstrap_admin()
        admin = await db.scalar(select(User).where(User.username == settings.initial_admin_username))
        if not admin:
            raise RuntimeError("Admin user was not created")

        severity_order = [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW, Severity.INFO]
        project_statuses = [ProjectStatus.ACTIVE, ProjectStatus.COMPLETED, ProjectStatus.ARCHIVED]

        for project_index in range(1, 11):
            project = Project(
                name=f"Demo Project {project_index}",
                description=f"Autogenerated demo project #{project_index}",
                status=project_statuses[(project_index - 1) % len(project_statuses)],
                created_by=admin.id,
            )
            db.add(project)
            await db.flush()

            db.add(ProjectMember(project_id=project.id, user_id=admin.id))

            for host_index in range(1, 3):
                host = Host(
                    project_id=project.id,
                    ip_address=f"10.{project_index}.{host_index}.10",
                    hostname=f"host-{project_index}-{host_index}.demo.local",
                    status=HostStatus.UP if host_index % 2 else HostStatus.UNKNOWN,
                    notes=f"Demo host notes for project {project_index}, host {host_index}",
                )
                db.add(host)
                await db.flush()

                for port_number in (22, 80, 443):
                    port = Port(host_id=host.id, port_number=port_number, protocol=Protocol.TCP, state=PortState.OPEN)
                    db.add(port)
                    await db.flush()
                    db.add(
                        Service(
                            port_id=port.id,
                            name="ssh" if port_number == 22 else "http",
                            version="OpenSSH_9.3" if port_number == 22 else "nginx/1.25",
                            banner=f"Demo banner for {port_number}",
                        )
                    )

                db.add(
                    Endpoint(
                        host_id=host.id,
                        path="/api/health",
                        method=HttpMethod.GET,
                        description="Health endpoint",
                    )
                )
                db.add(
                    Endpoint(
                        host_id=host.id,
                        path="/api/login",
                        method=HttpMethod.POST,
                        description="Authentication endpoint",
                    )
                )

                for vuln_index in range(1, 3):
                    vuln = Vulnerability(
                        project_id=project.id,
                        title=f"Vuln P{project_index}H{host_index}-{vuln_index}",
                        description="Autogenerated vulnerability for demo dataset",
                        severity=severity_order[(project_index + host_index + vuln_index) % len(severity_order)],
                        status=VulnerabilityStatus.OPEN,
                        created_by=admin.id,
                    )
                    db.add(vuln)
                    await db.flush()
                    db.add(
                        VulnerabilityAsset(
                            vulnerability_id=vuln.id,
                            asset_type=AssetType.HOST,
                            asset_id=host.id,
                        )
                    )

        await db.commit()


async def main() -> None:
    await reset_schema()
    await seed_demo_data()
    print("Database reset complete. Seeded admin/admin + 10 demo projects.")


if __name__ == "__main__":
    asyncio.run(main())
